name: Deploy Sratic Web App 

 on:
   push:
    branches :
    - main # Change this if your main 
    jobs:
      build_and_deploy:
        runs -on:ubuntu-latest 
          steps: 
            -name: Checkout repository 
            users: actions/checkout@v3
            - name : Build and Deploy 
            uses: Azure/Static-web-apps-deploy@v1
             with: 
             azure_static_web_apps_api_token: ${{
             secrets.AZURE_STATIC_WEB_APPS_API_TOKEN}}
             repo_token: ${{
             secrets.GITHUB_TOKEN}}
             action:"upload"
             app_location:"/"
             output_location:"dist"
